Repository michaelkhoe/harmoni, pull requests merged in 2025-01, with the labels that each got.

#1 add open api
  frontapi/build.gradle
  frontapi/src/main/java/com/harmoni/frontapi/configuration/OpenApiConfig.java
Labels: tools

#4 initialize react web app
  docker-compose.yml
  web/.gitignore
  web/Dockerfile
  web/README.md
  web/eslint.config.js
  web/index.html
  web/package-lock.json
  web/package.json
  web/public/vite.svg
  web/src/App.css
  web/src/App.tsx
  web/src/assets/react.svg
  web/src/index.css
  web/src/main.tsx
  web/src/vite-env.d.ts
  web/tsconfig.app.json
  web/tsconfig.json
  web/tsconfig.node.json
  web/vite.config.ts
Labels: enhancement

#5 add login screen
  web/package-lock.json
  web/package.json
  web/src/App.tsx
  web/src/components/Login.tsx
  web/src/styles/login.css
Labels: feature

#3 wrap all response in baseResponse
  frontapi/src/main/java/com/harmoni/frontapi/main/common/ErrorPayload.java
  frontapi/src/main/java/com/harmoni/frontapi/main/common/FrontApiGenericResponse.java
  frontapi/src/main/java/com/harmoni/frontapi/main/common/ResponseHeader.java
  frontapi/src/main/java/com/harmoni/frontapi/main/common/ResponsePayload.java
  frontapi/src/main/java/com/harmoni/frontapi/main/customer/controller/CustomerController.java
  frontapi/src/main/java/com/harmoni/frontapi/main/customer/service/CustomerService.java
  frontapi/src/main/java/com/harmoni/frontapi/main/product/controller/ProductController.java
  frontapi/src/main/java/com/harmoni/frontapi/main/product/service/ProductService.java
  frontapi/src/main/java/com/harmoni/frontapi/main/product/service/dao/DevProductDaoService.java
  frontapi/src/main/java/com/harmoni/frontapi/main/product/service/dao/ProductDao.java
  frontapi/src/main/java/com/harmoni/frontapi/main/transaction/controller/TransactionController.java
  frontapi/src/main/java/com/harmoni/frontapi/main/transaction/service/TransactionService.java
  frontapi/src/main/java/com/harmoni/frontapi/main/user/controller/UserController.java
  frontapi/src/main/java/com/harmoni/frontapi/main/user/service/UserService.java
Labels: enhancement

#2 add customer & transaction controller
  frontapi/src/main/java/com/harmoni/frontapi/main/common/ErrorPayload.java
  frontapi/src/main/java/com/harmoni/frontapi/main/common/FrontApiGenericResponse.java
  frontapi/src/main/java/com/harmoni/frontapi/main/common/ResponseHeader.java
  frontapi/src/main/java/com/harmoni/frontapi/main/common/ResponsePayload.java
  frontapi/src/main/java/com/harmoni/frontapi/main/customer/controller/CustomerController.java
  frontapi/src/main/java/com/harmoni/frontapi/main/customer/service/CustomerService.java
  frontapi/src/main/java/com/harmoni/frontapi/main/customer/service/dao/CustomerDao.java
  frontapi/src/main/java/com/harmoni/frontapi/main/customer/service/dao/DevCustomerDaoService.java
  frontapi/src/main/java/com/harmoni/frontapi/main/customer/service/model/Customer.java
  frontapi/src/main/java/com/harmoni/frontapi/main/product/controller/ProductController.java
  frontapi/src/main/java/com/harmoni/frontapi/main/product/service/ProductService.java
  frontapi/src/main/java/com/harmoni/frontapi/main/product/service/dao/DevProductDaoService.java
  frontapi/src/main/java/com/harmoni/frontapi/main/product/service/dao/ProductDao.java
  frontapi/src/main/java/com/harmoni/frontapi/main/transaction/controller/TransactionController.java
  frontapi/src/main/java/com/harmoni/frontapi/main/transaction/service/TransactionService.java
  frontapi/src/main/java/com/harmoni/frontapi/main/transaction/service/dao/DevTransactionDaoService.java
  frontapi/src/main/java/com/harmoni/frontapi/main/transaction/service/dao/TransactionDao.java
  frontapi/src/main/java/com/harmoni/frontapi/main/transaction/service/model/PaymentMethod.java
  frontapi/src/main/java/com/harmoni/frontapi/main/transaction/service/model/Transaction.java
  frontapi/src/main/java/com/harmoni/frontapi/main/transaction/service/model/TransactionItem.java
  frontapi/src/main/java/com/harmoni/frontapi/main/user/controller/UserController.java
  frontapi/src/main/java/com/harmoni/frontapi/main/user/service/UserService.java
Labels: enhancement

#12 init workflow file
  .github/workflows/frontapi_ci_check.yml
Labels: github-action

#13 init react-native
  mobile/.gitignore
  mobile/README.md
  mobile/app.json
  mobile/app/(tabs)/_layout.tsx
  mobile/app/(tabs)/explore.tsx
  mobile/app/(tabs)/index.tsx
  mobile/app/+not-found.tsx
  mobile/app/_layout.tsx
  mobile/assets/fonts/SpaceMono-Regular.ttf
  mobile/assets/images/adaptive-icon.png
  mobile/assets/images/favicon.png
  mobile/assets/images/icon.png
  mobile/assets/images/partial-react-logo.png
  mobile/assets/images/react-logo.png
  mobile/assets/images/react-logo@2x.png
  mobile/assets/images/react-logo@3x.png
  mobile/assets/images/splash-icon.png
  mobile/components/Collapsible.tsx
  mobile/components/ExternalLink.tsx
  mobile/components/HapticTab.tsx
  mobile/components/HelloWave.tsx
  mobile/components/ParallaxScrollView.tsx
  mobile/components/ThemedText.tsx
  mobile/components/ThemedView.tsx
  mobile/components/__tests__/ThemedText-test.tsx
  mobile/components/__tests__/__snapshots__/ThemedText-test.tsx.snap
  mobile/components/ui/IconSymbol.ios.tsx
  mobile/components/ui/IconSymbol.tsx
  mobile/components/ui/TabBarBackground.ios.tsx
  mobile/components/ui/TabBarBackground.tsx
  mobile/constants/Colors.ts
  mobile/hooks/useColorScheme.ts
  mobile/hooks/useColorScheme.web.ts
  mobile/hooks/useThemeColor.ts
  mobile/package-lock.json
  mobile/package.json
  mobile/scripts/reset-project.js
  mobile/tsconfig.json
Labels: mobile
